### ISSUE TITLE
No trigger on probe

### ISSUE THREAD

**Issue by bodydropped72** [1coderookie/Klipper4KobraGoNeo#12]
https://i.ibb.co/SJrGCrn/IMG-7344.jpg
https://i.ibb.co/ypzShtk/IMG-7343.jpg

getting this error after copy and pasted your specific printer.cfg into my config. is the probe not turning on? Happens on screws tilt adjust and bed mesh calibration.

**Comment by 1coderookie** [comment]
Probe should turn on (in terms of that it's properly activated in the cfg).  

Did you  
a) [level the ABL sensor in relation to the nozzle](https://1coderookie.github.io/KobraGoNeoInsights/hardware/printhead/#leveling-the-abl-sensor_1),  
b) already executed the `PROBE_CALIBRATE` and `Z_ENDSTOP_CALIBRATE` (see short description [here](https://1coderookie.github.io/KobraGoNeoInsights/firmware/fw_klipper/#z-offset))?   

If so and the error still occurs, increase the value `position_min: -2` in the `[stepper_z]` section of the cfg - might be that it just doesn't go down far enough.

**Comment by bodydropped72** [comment]
ok so i got probe to activate. this z endstop calibrate is pulling the life out of me. i followed klipper documentation to the T and i swear ive adjusted the z on the fly more than 15mm it seems like.

**Comment by 1coderookie** [comment]
And what was the solution then to get the probe being triggered? Increasing position:min? 
The position of the lever which triggers the z-endstop is different across the machines, and at mine I installed an individual one anyway. So that you have to check the settings and adjust them to your machine is usual as mentioned.  
Read the chapter about the z-offset at my infosite I linked to above. There's a difference betwenn Z_ENDSTOP_CALIBRATE which is for the printing z-offset and the PROBE_CALIBRATE which is for the z-offset of the probe itself.

**Comment by bodydropped72** [comment]
yes i went -10. getting this when trying to upload sliced file

 "Moonraker warnings found.
GCode path received from Klipper does not match expected location.

Received: '/home/biqu/printer_data/gcodes'
Expected: '/home/biqu/printer2_data/gcodes'

Modify the [virtual_sdcard] section Klipper's configuration to correct this error.

[virtual_sdcard]
path: /home/biqu/printer2_data/gcodes"

and here what my printer.cfg shows

"[include fluidd.cfg]
[virtual_sdcard]
path: /home/biqu/printer2_data/gcodes
on_error_gcode: CANCEL_PRINT

[mcu]
serial: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"

**Comment by bodydropped72** [comment]
also im running another printer off of this pad7 with no issues...

**Comment by 1coderookie** [comment]
Ok, thx for confirming about position:min. I added a note in the cfg file.  

As for your problem with the virtual_sdcard: is there another entry in the fluidd.cfg which has to be changed as well maybe? Cuz that entry is actually located in my mainsail.cfg, not in my printer.cfg.. 

As your initial issue is solved, I'll close this one now. 
Would be nice if you still post the solution about your virtual_sdcard problem here then, just that I know what it was in the end..
