### ISSUE TITLE
Prints fine, but screen is black

### ISSUE THREAD

**Issue by miffe** [1coderookie/Klipper4KobraGoNeo#17]
Hello,

I installed klipper_v0.12.0-10-gea2f6bc0.bin on my Neo, it prints just fine. But the screen stays black all the time. Is there a fix for this?

If not, how can I do things like load/unload filament?

**Comment by 1coderookie** [comment]
Hi,
the stock screen doesn't work with Klipper, as mentioned [here](https://1coderookie.github.io/KobraGoNeoInsights/firmware/fw_klipper/#stock-control-unit) for example. To load/unload filament, you can either write a macro or just manually heat up the hotend and pull out/push in the filament. I personally do it manually and combine the removing with a cold pull.
