### ISSUE TITLE
Weird thing in my firmware flashing

### ISSUE THREAD

**Issue by jhi2** [1coderookie/Klipper4KobraGoNeo#20]
When I flash my firmware, instead of staying black, it says:
`UpdateFirmware`
Is this normal?
Thank you!

**Comment by 1coderookie** [comment]
Yes, that's totally fine. Just wait a few minutes and then you can continue.  
You know the infosite about the Go/Neo I reckon? Just in case you don't, here you go, there's also a chapter about Klipper: https://1coderookie.github.io/KobraGoNeoInsights
