### ISSUE TITLE
kobra neo firmware

### ISSUE THREAD

**Issue by bodydropped72** [1coderookie/Klipper4KobraGoNeo#5]
ive downloaded the .bin file but my printer isnt recognizing it. ive read that stock board will work but now im doubting it. any insight on what i might be doing wrong

**Comment by 1coderookie** [comment]
What *exactly* was your procedure?
The stock mb does work with it, me and many other users are running Klipper on the stock mb..

**Comment by bodydropped72** [comment]
i followed the procedure  as stated in the readme file. download the klipper.bin file to firmware.bin put on microsd with printer off, turn printer on, screen comes on as normal.

**Comment by bodydropped72** [comment]
that was yesterday, as of today i have reformatted sdcard reinstalled .bin file and now after inserting sdcard and turning machine on display comes on as normal and shows sd init fail. i then removed card with machine on and reinserted it to know its connected. turned the machine off then back on and it again shows sd init fail

**Comment by 1coderookie** [comment]
Hmmm, that's weird, as other users had no problem with it.
I'd suggest to download the whole repo as a zip and unzip it, just to make sure everthing went right there:
![Bildschirmfoto von 2023-04-24 19-08-02](https://user-images.githubusercontent.com/25869362/234067588-dedfd56e-ea34-473a-9bff-09450b2626f1.png)
Then rename klipper.bin to firmware.bin and copy it on an empty card, no subdirectories or so. 
That the screen comes on is normal, but  then it should go in the flashing routine and stay there as mentioned in the belonging Klipper chapter at the page (https://1coderookie.github.io/KobraGoNeoInsights/firmware/fw_klipper/#installation).
Then just wait like 10min and then it should be good.

**Comment by 1coderookie** [comment]
Did you format it as FAT?

**Comment by 1coderookie** [comment]
I personally had to try four or five different cards until the control unit finally accepted one.. 
How big is your card?

**Comment by 1coderookie** [comment]
The .rar isn't what you're using for flashing, also from the stock fw you'd have to make a .bin file out of for flashing it..

**Comment by bodydropped72** [comment]
i have a 32gb sandisk formatted to fat32

**Comment by 1coderookie** [comment]
> what if i restore board to factory or update using anycubics firmware then try it again?

Wait - so when you're talking about restore to factory etc, then that actually kinda sounds like you already flashed klipper onto it..?!
So what does happen if you just turn on the printer without the card? Does it start normal loading the stock firmware? If so, then try different cards as mentioned.

**Comment by bodydropped72** [comment]
ill have to go purchase one. ill give it a shot and let you know. thanks for the help!

**Comment by 1coderookie** [comment]
Btw: removing and inserting the card when the printer is switched on isn't a good idea as that will most likely destroy the filesystem..
So maybe try it again with this card. Do a **full format** (*not only 'quick'*) FAT32, copy the .bin file onto it as described, stick it in with the printer turned off and then turn it on.

**Comment by bodydropped72** [comment]
ill do a long reformat and try again. all of my retailers here dont have any cards lower than 32gb so ill be ordering.

**Comment by 1coderookie** [comment]
Well, it *should* work with a card max 32GB as well, but as I said, I had to try many cards until it finally accepted one. Is that the card that came with the printer? Maybe you have an old card from an old smartphone laying around as well..

**Comment by bodydropped72** [comment]
hello, i have receieved some new sd cards. it seems to have worked? i turned the printer on after installing the card and the screen is now black. But according to the instuction it should say firmware update
